import type { Metadata } from "next";
import "@/app/globals.scss";
import { interTight } from "@/app/ui/fonts";
import NavBar from "@/app/ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={interTight.className}>
        <NavBar />
        {children}
        </body>
    </html>
  );
}
